### ISSUE TITLE
grid of standout projects is off?

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/taaccct#3] opened 2015-03-10 19:33 UTC
eg. blank spaces where there shouldn't be on Firefox 36.0.1
![open4us screenshot](https://cloud.githubusercontent.com/assets/6394777/6583468/9a1af69e-c721-11e4-8587-e6178de4c26d.jpg)

**Comment by mattl** [comment] 2015-03-10 19:34
duplicate of #1 (i need to write better issue descriptions)

**Closed as completed by mattl** 2015-03-10 19:34 UTC
